---
label: "wien2k-init_lapw"
description: "wien2k init_lapw"
input_plugin: "wien2k-init_lapw"
on_computer: true
remote_abs_path: "/area51/WIEN2k_21/init_lapw"
computer: "localhost"
prepend_text: '
export EDITOR="vim";
export SCRATCH=./;
mkdir -p case && cd case'
append_text: " "
