---
label: "wien2k-run_lapw"
description: "wien2k run_lapw"
input_plugin: "wien2k-run_lapw"
on_computer: true
remote_abs_path: "/area51/WIEN2k_21/run_lapw"
computer: "localhost"
prepend_text: '
export EDITOR="vim";
[[ -z "${SLURM_JOB_NAME}" ]] && export SCRATCH="/scratch/aiida/${RANDOM}" || export SCRATCH="/scratch/aiida/${SLURM_JOB_NAME}";
mkdir -p ${SCRATCH}
mkdir -p case && cd case'
append_text: " "
