---
label: "wien2k-run_lapw_clmextrapol"
description: "wien2k run_lapw with clmextrapol"
input_plugin: "wien2k-run_lapw_clmextrapol"
on_computer: true
remote_abs_path: "/area51/WIEN2k_21/run_lapw"
computer: "localhost"
prepend_text: '
export EDITOR="vim";
[[ -z "${SLURM_JOB_NAME}" ]] && export SCRATCH="/scratch/aiida/${RANDOM}" || export SCRATCH="/scratch/aiida/${SLURM_JOB_NAME}";
mkdir -p ${SCRATCH}
mkdir -p case && cd case;
mv ../case.struct .;
rm -f *.broy* *.scf* :log *.day* *.error* *.log;
clmextrapol_lapw;
sed -i -e "1s/BY.../BY  0/" case.clmsum'
append_text: " "
