---
label: "localhost"
hostname: "localhost"
transport: local
scheduler: "direct"
work_dir: "/eos/rubel/lapw"
shebang: "#!/bin/bash"
mpirun_command: "mpirun -np {tot_num_mpiprocs}"
mpiprocs_per_machine: "2"
prepend_text: " "
append_text: " "
description: "localhost"
